---
- name: Create EC2 security group
  ec2_group:
    name: "{{ ec2_security_group }}"
    description: all ports open
    region: "{{ ec2_region }}"
    vpc_id: "{{ ec2_vpc_id }}"
    rules:
      - proto: all
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  when: ec2_exact_count >= 1
  tags:
    - always
    - provision

- name: Create or destroy EC2 instances
  ec2:
    assign_public_ip: yes
    key_name: "{{ ec2_key_name }}"
    group: "{{ ec2_security_group }}"
    instance_type: "{{ item.instance_type }}"
    image: "{{ item.image }}"
    region: "{{ ec2_region }}"
    exact_count: "{{ ec2_exact_count }}"
    count_tag:
      name: "{{ ec2_name_prefix }}-{{ item.pod_name | default('') }}-{{ item.role }}-{{ item.name }}"
    instance_tags:
      name: "{{ ec2_name_prefix }}-{{ item.pod_name | default('') }}-{{ item.role }}-{{ item.name }}"
      environment: "{{ environment | default('') }}"
      role: "{{ item.role }}"
      app: "{{ item.app_name }}"
      pod: "{{ item.pod_name | default('') }}"
      user: "{{ item.username | default('') }}"
    wait: "{{ ec2_wait }}"
    vpc_subnet_id: "{{ ec2_vpc_subnet_id | default(omit) }}"
    user_data: "{{ item.user_data | default(omit) }}"
    volumes: "{{ item.volumes | default(omit) }}"
  with_items:
    - "{{ nodes }}"
  register: ec2_jobs
  async: 7200
  poll: 0
  tags:
    - always
    - provision

- name: Wait for instance creation to complete
  async_status: jid="{{ item.ansible_job_id }}"
  register: instances
  until: instances.finished
  retries: 300
  with_items: "{{ ec2_jobs.results }}"
  tags:
    - always
    - provision

#- name: Waiting for servers to come online
#  wait_for:
#    host: "{{ item.tagged_instances[0].public_ip }}"
#    port: "{{ ansible_port }}"
#    timeout: 300
#  with_items: "{{ instances.results }}"
#  when: instances | changed and ec2_exact_count >= 1
#  tags:
#    - always
#    - provision

- name: Waiting for servers to come online
  wait_for_connection:
  with_items: "{{ instances.results }}"
  delegate_to: "{{ item.tagged_instances[0].public_ip }}"
  when: instances | changed and ec2_exact_count >= 1 and ansible_version.full | version_compare('2.4', '>=')
  tags:
    - always
    - provision

- name: Waiting for servers to come online
  wait_for:
    host: "{{ item.tagged_instances[0].public_ip }}"
    port: "{{ ansible_port }}"
    timeout: 300
  with_items: "{{ instances.results }}"
  when: instances | changed and ec2_exact_count >= 1 and ansible_version.full | version_compare('2.4', '<')
  tags:
    - always
    - provision
